server:
    port: 8080

spring:
    datasource:
        name: night
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/night?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
        username: night
        password: night
    thymeleaf:
        prefix: classpath:/templates/
        check-template-location: true
        suffix: .html
        encoding: UTF-8
        mode: LEGACYHTML5
        cache: false
    aop:
        auto: true
        proxy-target-class: true
    servlet:
        multipart:
        max-file-size: 10Mb
        max-request-size: 100Mb
    devtools:
        restart:
            enabled: true #热部署生效

## 该配置节点为独立的节点
mybatis:
    mapper-locations: classpath:mapping/**/*.xml
    type-aliases-package: com.index

logging:
    config: classpath:logback-spring.xml
    level:
        org:
            mybatis: debug
            springframework:
               web: debug

swagger:
    show: true

## 访问本地配置文件
configfile: config.properties

## 访问本地资源路径配置（以/结尾）
localfile:
    picturePath: file:///G:/視頻/夜色网/
    videoPath: file:///G:/視頻/
    uploadPicturePath: G:/視頻/夜色网/
    uploadVideoPath: G:/視頻/
    ffmpegPath: static\plugins\ffmpeg\bin\ffmpeg.exe